export const getServices = () => {
    return [
        {
            titre: "Conseil et Formation",
            navSlug: "conseil-formation",
            metaTitle: "Formation Informatique Professionnelle au Puy-de-Dôme - GuillaumeWeb",
            description: "Profitez de mon expertise locale pour votre réussite numérique. Je travaille avec tous les niveaux de compétences et je m'adapte à vos besoins.",
            mainContent: "<section><p> Vous avez peut-être lu mon parcours et vous savez donc que l'informatique et moi, c'est une histoire de longue date. Maintenant, je suis là pour vous accompagner dans votre propre aventure numérique.</p></section> <section><h2>Particuliers : Plongez dans le Numérique</h2>      <p>Vous cherchez à vous familiariser avec les bases de l'informatique ou à élever votre niveau ? Ensemble, nous allons décrypter les mystères du monde digital. Que vous soyez novice ou simplement à la recherche de nouvelles compétences, je suis là pour vous guider.</p></section><section> <h2>Petites Entreprises : La Transition Numérique, Pas à Pas</h2><p>L'ère numérique est là. Mais par où commencer ? De la mise en place d'un réseau interne à la création d'un site web dynamique, je vous aide à mettre le pied à l'étrier.</p> </section> <section> <h2>Futurs Développeurs : Préparez-vous au Futur</h2> <p>Si vous êtes dans un centre de formation ou cherchez à évoluer dans votre carrière, je vous propose des sessions pour maîtriser les outils et les langages les plus demandés sur le marché.</p> </section> <section> <h2>Pourquoi choisir mes formations au Puy-de-Dôme ?</h2> <ul><li><strong>Proximité :</strong> Implanté au cœur du Puy-de-Dôme, je connais les spécificités de la région.</li><li><strong>Adaptabilité :</strong> Des sessions taillées sur mesure pour répondre à vos besoins spécifiques.</li> <li><strong>Expérience :</strong> Fort d'un parcours riche et diversifié, je mets mon savoir-faire à votre service.</li> </ul>        <p>N'attendez plus. Explorez, apprenez et grandissez dans le monde numérique. Contactez-moi et démarrons cette aventure ensemble.</p></section>",
            image: "<i class=\"bi bi-easel-fill\"></i>"
        },
        {
            titre: "Création de site Internet",
            navSlug: "site-internet",
            metaTitle: "Création de site internet dans le Puy de Dôme - GuillaumeWeb",
            description: "Vous avez besoin d'un site web ? Je vous propose des solutions sur mesure pour répondre à vos besoins.",
            mainContent: "<section> <h2> Site web sur mesure</h2><p>Je propose une gamme variée de services, incluant : </p> <ul> <li>Design réactif pour une navigation fluide sur tous les appareils </li> <li> Optimisation SEO pour améliorer votre visibilité </li><li> Formation à la maintenance du site via WordPress, vous permettant de gérer votre contenu de manière autonome, réduisant ainsi les coûts de maintenance.</li></ul></section><section><h2>Pourquoi choisir GuillaumeWeb ?</h2><p>Choisir GuillaumeWeb, c'est opter pour une approche centrée sur l'accompagnement et l'autonomie :</p><ul><li><strong>Coût de maintenance réduit</strong> : Grâce à l'utilisation de WordPress et à la formation personnalisée que je fournis, vous pouvez gérer votre site de manière autonome.</li><li><strong>Accompagnement global</strong> : Je vous accompagne à chaque étape de votre projet, depuis la conception initiale jusqu'à la maintenance et au-delà, vous assurant une présence en ligne pérenne et évolutive.</li></ul></section>",
            image: "<i class=\"bi bi-code-slash\"></i>"
        },
        {
            titre: "Développement Informatique",
            navSlug: "developpement",
            metaTitle: "Développement d'application web et mobile au Puy-de-Dôme - GuillaumeWeb",
            description: "Spécialiste en JavaScript, je propose des solutions sur mesure pour tous vos besoins en applications web et mobiles.",
            mainContent: "<section><p>Dans le monde du développement d'applications, le JavaScript est un pilier incontournable. Spécialiste en JavaScript, je suis GuillaumeWeb, votre expert en création d'applications web et mobiles sur mesure, capables de répondre à tout défi technique ou fonctionnel.</p></section><section><h2>Expertise en JavaScript</h2><p>Avec une maîtrise approfondie du JavaScript et de ses frameworks les plus populaires (Vue, Node.js pour le développement web, electronJs pour les applications), je vous assure une solution optimale et innovante pour chaque aspect de votre projet.</p></section><section><h2>Solutions personnalisées</h2><p>Je propose une gamme complète de services, adaptée à vos besoins spécifiques :</p> <ul><li><strong>Développement d'applications web</strong> : Tirant parti de frameworks JavaScript avancés pour créer des sites web dynamiques, performants et SEO-friendly.</li> <li><strong>Développement d'applications mobiles</strong> : Conception d'applications mobiles réactives, utilisant JavaScript pour une compatibilité cross-platform (iOS et Android).</li><li><strong>Consultation technique et résolution de problèmes</strong> : Grâce à une compréhension approfondie de JavaScript, je trouve et implémente des solutions à des défis complexes, assurant la réussite de votre projet.</li> </ul> </section><section><h2>Approche orientée solution</h2><p>Je crois fermement qu'il existe une solution JavaScript pour chaque problème. Mon approche consiste à comprendre en profondeur vos défis pour vous offrir une réponse sur mesure qui non seulement résout le problème mais optimise également votre présence en ligne.</p></section>",
            image: "<i class=\"bi bi-code-slash\"></i>"
        }
    ]
}
